#!/usr/bin/with-contenv bash

if [ ! -a /config/www/active-github-fork.lock ]; then
  echo "**** Installing Active-GitHub-Forks  ****"
  rm -Rf /config/www/*
  git clone \
    https://github.com/techgaun/active-forks.git \
      /config/www
  touch /config/www/active-github-fork.lock
  chown -R abc:abc \
    /config/www
else
  echo "**** Active-GitHub-Forks already installed, skipping  ****"
fi